steps:
  - name: node:16
    entrypoint: "yarn"
    args: ["install"]
  - name: node:16
    entrypoint: "./node_modules/.bin/expo"
    args: ["build:web"]
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: "bash"
    args: ["-c", "gcloud config set app/cloud_build_timeout 1600 && gcloud app deploy"]
    timeout: "1600s"